### ISSUE TITLE
I have added some features. May I contribute?

### ISSUE THREAD

**Issue by xvitus** [firebirdberlin/nightdream#138]
1. I have made Locked state to not affect snooze or brightness setting, so you can snooze or change brightness in locked state also.
2. Fixed locked state alarm tap responsiveness (I have found that sometimes alarm tap responded opening alarm settings, also if locked, so I fixed it).

I have made such modifications and tested on emulator and my device (Galaxy Note 4). May I contribute the main trunk in any way?

Best Regards,
--Vito.

**Comment by firebirdberlin** [comment]
Hi Vito, 

contributions are highly appreciated. Just fork my repo and create an own branch in order to make a pull request. Usually we create an issue and add a branch with a name starting with the corresponding issue number. 

I am not sure if changing the brightness from the locked state is a good idea because the locked state shall prevent unwanted interaction. Snoozing alarms from the lock screen seems reasonable to me. 

Stefan :)

**Comment by xvitus** [comment]
Hi Stefan,

Thank you for your kind reply.
I will do what you suggest.

As for the brightness during lock, my (peculiar) use case follows:

I appreciate lock for avoiding to inadvertently turn-off or change the
alarm, once set.
I use high brightness to setup all things before going to bed (i am nearly
50 of age, so I need glasses and brightness ;-)).
So, I set the alarm and then* lock to be sure I won't mess with alarm
settings anymore*.
Then I turn off the light in the room and finally adjust the brighness so
that is barely visible.

Regards,
--Vito


2018-05-15 13:41 GMT+02:00 Stefan Fruhner <notifications@github.com>:

**Comment by firebirdberlin** [comment]
I think another option is to activate the screen lock after a certain time of inactivity. This way the user cannot forget to lock the screen and we don't have to overrule the locking mechanism.

**Comment by xvitus** [comment]
My personal neeed for a lock (for which I made the modification) is to only
lock the alarm settings.
This must happen immediately: I set the alarm, then I lock the screen, then
I double check the alarm setting, then I put the phone on the bedside table
with peace of mind, not risking to alter/disable the alarm while handling
the phone to the bedside table (some mornings happened I found the alarm
was disabled).
Personally, I don't feel the need to lock anything else than the alarm
settings and the enable (and the setting menus, of course).
Just my 2c.
--Vito.


2018-05-31 10:44 GMT+02:00 Stefan Fruhner <notifications@github.com>:

**Comment by firebirdberlin** [comment]
The main reason for the lock screen feature is that the standby mode may be activated when the device is not charging. In this case the device my be placed within a pocket where the user is not aware of interacting with the UI.

**Comment by xvitus** [comment]
I didn't realize that it is possible that the app will activate itself in
such a manner. In fact I see the options for automatic activation (that I
don't use).
Maybe the solution could be adding some more settings:

"Locked screen allows snooze ON/OFF"
"Locked screen allows dimming setting ON/OFF"
"Locked screen allows resize ON/OFF"

(all with default=off).



Il giorno lun 4 giu 2018 alle ore 09:51 Stefan Fruhner <
notifications@github.com> ha scritto:

**Comment by firebirdberlin** [comment]
That would by an option. We should keep in mind that we cannot provide translations. Every option we add is not translated until a volunteer helps us. 

As a start I would suggest, to allow snoozing alarm while the device is locked. Thus the device is quiet as soon as possible. In order to delete the snoozed alarm, the device must be unlocked. This way we ensure the user ends the alarm intentionally. 

With this scenario we may not have to add another preference. What do you think about it ? 

Stefan

**Comment by xvitus** [comment]
I would prefer to allow also during device locked:

   - brightness change
   - resize
   - snooze (as you propose)

fundamentally *leaving the lock affect the menu and the alarm
setting/enable/disable only*.
--Vito.

Il giorno gio 14 giu 2018 alle ore 16:03 Stefan Fruhner <
notifications@github.com> ha scritto:
