### ISSUE TITLE
The app sporatically terminates while charging

### ISSUE THREAD

**Issue by Fischreiher** [firebirdberlin/nightdream#217]
Hi, I'm using my second phone as a night clock. I'm keeping it on a wireless charger, and I would like the clock to be permanently on.
In this use case, I have seen the following issue:

The app sporatically terminates while charging.

This could be related to
    `triggerAlwaysOnTimeout():`
where the variable `timeout` is only used for logging, not in the last line
`handler.postDelayed(alwaysOnTimeout, 60000 * mySettings.batteryTimeout);`

However I'm not sure whether this really explains the issue, nor whether using `timeout` there, resulting in termination after MINIMUM_APP_RUN_TIME_MILLIS, is any better.

I have disabled the last line in my own build, and I have not seen sporatically termination since.

Thanks a lot! Great App!

**Comment by Fischreiher** [comment]
I will create a separate Issue for #3 for better tracability.

**Comment by firebirdberlin** [comment]
Hey @Fischreiher, sorry für replying so late. I really appreciate your efforts. Distinct tickets for different issues would be great so that I can focus better in one of them. Issues with wireless chargers will be difficult to resolve as I don't own such a device. Can you help to investigate ? For more detailed discussions I'd like to invite you to our Slack workspace. If you send me an email to stefan.fruhner@googlemail.com I will send you an invitation.

**Comment by Fischreiher** [comment]
Thanks, I have sent you an email, and I have separated the issues.

**Comment by firebirdberlin** [comment]
solved
