### ISSUE TITLE
Add custom stream urls

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#98]
Some radio streams cannot be found using the dirble API. Allow to add a custom URL. 

Include this into the dialog.

**Comment by martinposchmann** [comment]
The search dialog now contains a link which opens another dialog for manually entering a stream url and description. Urls ending with .m3u or .pls are assumed to be in m3u or pls format, otherwise plain stream urls. m3u and pls urls are verified and parsed. the description of the stream can be customized afterwards.

To Do:
* check if stream url is reachable/live when pressing ok?
* show and initialized this dialog when opening radio stream preferences? (additionally store .m3u/.pls url name in preferences)
